---
title: "large_testing_file"
author: "mky"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1

```{r}
test1 <- function(processed_annotation, processed_data, cluster_output) {
  processed_data |>
    mutate(cluster = paste0("Group_", cluster_output[[1]]$cluster)) |>
    select(c("ID", "cluster")) |>
    merge(processed_annotation, by = "ID", all.x = TRUE)
}

test <- test1(pathchee,cheesedata,cluschee)

test2_dfgroup_long <- function(processed_data, clusters_output, processed_annotation) {
  maindata <- processed_data |>
    mutate(cluster = paste0("Group_", clusters_output[[1]]$cluster)) |>
    pivot_longer(
      c(-ID, -cluster, -type),
      names_to = "day",
      values_to = "value"
    ) |>
    mutate(day = factor(day, levels = colnames(processed_data)[c(-1, -ncol(processed_data))])) |>
    left_join(select(processed_annotation, ID, taxonomic.scope), by = "ID")

  maindata$taxonomic.scope[is.na(maindata$taxonomic.scope)] <- "No Label"
  maindata
}

test2_dfgroup_long(cheesedata,cluschee,pathchee)


intermediate_variable_generator <- function(processed_annotation, processed_data, cluster_output, network_output){
  ivs <- list()
  #对齐数量（na）
  ptw <- processed_data |>
    mutate(cluster = paste0("Group_", cluster_output[[1]]$cluster))|>
    merge(processed_annotation, by = "ID", all.x = TRUE)
  
}



```

```{r}

pathchee <- gAnnotation(annotations,phylum,class,KEGG_ID)

summary(as.factor(pathchee$taxonomic.scope))
```



# dashboard



```{r}
data('cheese')

```

```{r}
annotations <- merge(f12,t12,by="ID")

cheese <- c12

save(cheese,annotations,file="cheese.RData")
```


# 2
```{r}
data("cheese")
library(MolPad)

cheesedata <- cheese |>
  dplyr::mutate(annotations["kingdom"]) |>
  dplyr::rename(type=kingdom) |>
  pre_process()

cluschee <- gClusters(cheesedata,ncluster = 10,elbow.max=15)
networkchee <- gNetwork(cluschee,ntop = 3)

pathchee <- gAnnotation(annotations,phylum,class,KEGG_ID)


gDashboard(cheesedata,cluschee,pathchee,networkchee,dashboardtitle = "Test",id_colname = c("GO_ID","web_id"),id_type = c("GO","KEGG"))

#-----

```
```{r}
test<-pathchee[1:13,]
test$GO_ID

match_database <- function(data,id_colname,id_type){
  if(length(id_colname)!=length(id_type)){
    print("id_colname and id_type must have the same length.")
  }else{
    for (i in 1:length(id_colname)) {
      data[[id_colname[i]]] <-  paste_URL(data[[id_colname[i]]],id_type[i])
    }
    data
  }
}

rm(match_database)
test1 <- c("kk","uu")
test1[1]
match_database(test,id_colname = c("GO_ID","web_id"),id_type = c("GO","KEGG"))

str_extract_all(test$GO_ID,"GO:\\d{7}")
paste_URL(test$GO_ID,"GO")

output_tableview$web_id <- paste_URL(output_tableview$web_id,id_type)
```


```{r}
test<-pathchee[1:10,c(1,3)]
test

gsub("K\\d{5}","link",test$web_id)
grep("K\\d{5}",test$web_id,value=TRUE)

paste0("<a href='", output_tableview$web_id, "' target='_blank'>", output_tableview$web_id, "</a>")


str_extract(test$web_id,"K\\d{5}")

test1 <- test$web_id[7]
test1
length(str_extract_all(test$web_id,"K\\d{5}")[[7]])
library(stringr)
paste0("<a href='",str_extract_all(test$web_id,"K\\d{5}"),"' target='_blank'>","</a>")

paste_URL <- function(x,id_type){
  output_list <- c()
  if(id_type=="KEGG"){
    extract_multiple_id <- str_extract_all(x,"K\\d{5}")
    link <- "https://www.kegg.jp/entry/"
  }else if(id_type=="GO"){
    extract_multiple_id <- str_extract_all(x,"GO:\\d{7}")
    link <- "https://www.ebi.ac.uk/QuickGO/term/"
  }else{
    print("ID must be one of the following: KEGG, GO")
  }
  for (i in 1:length(extract_multiple_id)) {
    if(length(extract_multiple_id[[i]]) != 0){
      for (j in 1:length(extract_multiple_id[[i]])) {
        extract_multiple_id[[i]][j] <- paste0("<a href='",link,extract_multiple_id[[i]][j],"' target='_blank'>",extract_multiple_id[[i]][j],"</a>")
      }
      output_list[i] <- paste(extract_multiple_id[[i]], collapse = '<br/>')
    }
  }
  output_list
}

rm(paste_URL)
test$web_id 
  
paste_URL(test$web_id,"KEGG")

test

test
lapply(test$web_id, paste_URL)
```



```{r}
test <- gPathway(pathchee, cheesedata, cluschee)



annotation_hyperlink2(test,id_type = "KEGG")

gMainData(cheesedata, cluschee, pathchee)

gMainData.test <- function(gpathway_output) {
  maindata <- gpathway_output |>
    pivot_longer(
      c(-ID, -cluster, -type),
      names_to = "day",
      values_to = "value"
    ) |>
    mutate(day = factor(day, levels = colnames(data)[c(-1, -ncol(data))])) |>
    left_join(select(pathway, ID, taxonomic.scope), by = "ID")

  maindata$taxonomic.scope[is.na(maindata$taxonomic.scope)] <- "No Label"
  maindata
}

gMainData.test(test)
```


# modify funcs
```{r}

annotation_hyperlink <- function(ptw, id_type) {
  nao_ptw <- na.omit(ptw)
  if(id_type == "KEGG"){
    nao_ptw[, "web_id"] <- paste0("https://www.kegg.jp/entry/", nao_ptw[, "web_id"])
  }else if(id_type == "GO"){
    nao_ptw[, "web_id"] <- paste0("https://www.ebi.ac.uk/QuickGO/term/", nao_ptw[, "web_id"])
  }
  nao_ptw[, "web_id"] <- paste0("<a href='", nao_ptw[, "web_id"], "' target='_blank'>", nao_ptw[, "web_id"], "</a>")
  nao_ptw
}

annotation_hyperlink2 <- function(ptw, id_type) {
  nao_ptw <- ptw
  if(id_type == "KEGG"){
    nao_ptw[, "web_id"] <- paste0("https://www.kegg.jp/entry/", nao_ptw[, "web_id"])
  }else if(id_type == "GO"){
    nao_ptw[, "web_id"] <- paste0("https://www.ebi.ac.uk/QuickGO/term/", nao_ptw[, "web_id"])
  }
  nao_ptw[, "web_id"] <- paste0("<a href='", nao_ptw[, "web_id"], "' target='_blank'>", nao_ptw[, "web_id"], "</a>")
  nao_ptw
}

gDashboard2 <- function(data, clusters, pathway, networkres,
                       dashboardtitle = "MolPad Dashboard", 
                       id_type = "KEGG") {
  ptw <- gPathway(pathway, data, clusters)
  dfgroup_long <- gMainData(data, clusters, ptw)

  nao_ptw <- annotation_hyperlink(ptw, id_type)
  
  uni_t <- unique(pathway$taxonomic.scope)
  uni_ptw <- unique(pathway$Pathway)
  css <- readLines(system.file("dashboard.css", package = "MolPad"))

  app <- list(
    ui =
      dashboardPage(
        dashboardHeader(title = dashboardtitle, titleWidth = 350),
        dashboardSidebar(
          width = 100,
          sidebarMenu(
            menuItem("Main", tabName = "dashboard", icon = icon("dashboard")),
            menuItem("Info", tabName = "widgets", icon = icon("eye"))
          )
        ),
        dashboardBody(
          tags$style(HTML(css)),
          tabItems(
            tabItem(
              tabName = "dashboard",
              fluidRow(
                box(column(4, selectInput("s_ptw", "Select a Functional Annotation:", uni_ptw)),
                  column(7, sliderInput("obs", "Importance Score:",
                    min = 0,
                    max = round(quantile(abs(networkres$weight))[4], 1),
                    value = round(quantile(abs(networkres$weight))[3], 1)
                  )),
                  plotOutput("plot", brush = brushOpts("plot_brush", fill = "#bd9fb7", stroke = "#85056d", opacity = 0.3), height = 410),
                  width = 7, height = 550
                ),
                tags$div(
                  id = "toto",
                  box(selectInput("s_tax", "Select a Taxonomic Scope:", uni_t, selected = NULL, multiple = TRUE),
                    plotOutput("plot3", height = 120),
                    plotOutput("plot2", height = 320),
                    width = 5, height = 550
                  )
                )
              ),
              fluidRow(
                tags$div(
                  id = "toto",
                  box(column(3, selectInput("s_p", "Filter by Functional Annotation:", uni_ptw, selected = as.factor(uni_ptw[1]))),
                    column(9, dataTableOutput("Observe_Out")),
                    width = 12
                  )
                )
              )
            ),
            tabItem(tabName = "widgets", h2("Info tab content"))
          )
        )
      ),
    server =
      function(input, output, session) {
        P1 <- reactive(
          make_the_graph(
            ptw,
            networkres,
            input$obs,
            input$s_ptw
          )
        )
        output$plot <- renderPlot(P1())

        group_names_selected <- reactive({
          if (is.null(input$plot_brush$xmin)) {
            "Group_2"
          } else {
            coords_filt()[, 1]
          }
        })

        taxa_selected <- reactive({
          if (is.null(input$s_tax)) {
            unique(dfgroup_long$taxonomic.scope)
          } else {
            input$s_tax
          }
        })

        output$plot2 <- renderPlot(
          make_line_plot(
            dfgroup_long,
            group_names_selected(),
            taxa_selected()
          )
        )
        coords_filt <- reactive({
          if (is.null(input$plot_brush$xmin)) {
            make_the_table(P1())[, -c(1, 2)] #test1-10lines
          } else {
            filter(
              make_the_table(P1()),
              x >= input$plot_brush$xmin,
              x <= input$plot_brush$xmax,
              y >= input$plot_brush$ymin,
              y <= input$plot_brush$ymax
            )[, -c(1:2)]
          }
        })

        output$plot3 <- renderPlot(
          make_stackbar_plot(
            dfgroup_long,
            group_names_selected(),
            taxa_selected()
          )
        )

        observe({
          updateSelectInput(
            session,
            "s_p",
            choices = unique(info_filt()[, 5]), selected = input$s_ptw
          )
        })

        info_filt <- reactive({
          if (is.null((input$plot_brush$xmin))) {
            nao_ptw[nao_ptw$cluster %in% coords_filt()[, 1], ][1:10, ]
          } else {
            if (is.null(input$s_tax)) {
              nao_ptw[nao_ptw$cluster %in% coords_filt()[, 1], ]
            } else {
              nao_ptw[nao_ptw$cluster %in% coords_filt()[, 1], ] |> filter(taxonomic.scope %in% input$s_tax)
            }
          }
        })

        output$Observe_Out <- renderDataTable({
          info_filt2 <- info_filt() |>
            filter(Pathway %in% input$s_p) |>
            select(-c("Pathway"))
          datatable(info_filt2, escape = FALSE, options = list(pageLength = 5))
        })

        brushed_grp <- reactive({
          if (is.null(input$plot_brush$xmin)) {
            unique(networkres$from)
          } else {
            unique(coords_filt$name)
          }
        })
      }
  )
  runApp(app)
}
```

# reshape
```{r}
reshape_for_make_functions(cheesedata,cluschee,pathchee,"KEGG")

```
