#' gAnnotation
#'
#' @description `gClusters` returns the 
#'
#' @details This function could 
#' 
#' @docType package
#' @name gAnnotation
#'
#' @param data A data frame generated by gData().
#' @param ncluster A number of clusters.
#' @param iter.max A number of the maximum iterations allowed in k-means.
#' @param nstart A number of random attempts of generating initial
#' configurations. The k-means algorithm will choose the best one among these
#' attempts. For larger data, 'nstart' can be set lower or just set to 1.
#' @param elbow.max A number of the maximum value of x-axis. It should be larger
#' than the expected `ncluster` and smaller than the sample size.
#'
#' @returns A list of 2:
#' @examples data(FuncExample)
#' @importFrom tidyr replace_na
#' @importFrom dplyr rename mutate_at
#' @export
gAnnotation <- function(data,first_order,second_order,identifier) {
  strings <- c(as.character(substitute(first_order)), 
               as.character(substitute(second_order)),
               as.character(substitute(identifier)))
  data %>%
    dplyr::rename("Pathway" = strings[1],
           "taxonomic.scope" = strings[2],
           "web_id" = strings[3]) %>%
    dplyr::mutate_at(c("Pathway","taxonomic.scope"), ~replace_na(.,"Unknown"))
}
