#' Generate clusters
#'
#' @description `gClusters()` returns the clusters generated by k-means and yield
#' an elbow plot as a way of finding the optimal parameter.
#'
#' @details 
#' To determine the optimal number of clusters (`ncluster`), it is advised to closely examine the elbow plot and identify the point on the graph where a substantial change or 'elbow' occurs. This is often indicative of the most suitable cluster count.
#' In cases where your dataset is extensive or intricate, you might consider increasing the value of `elbow.max` to ensure a more comprehensive exploration of potential cluster counts. This can help in achieving more accurate and meaningful results, especially when working with larger or more complex datasets.""This function can be executed with only the `data` parameter at the outset. However, to achieve the best clustering results, further adjustments are recommended. After the initial run, users are expected to adjust the function's parameters based on the clustering outcomes and the elbow plot analysis.
#' 
#' @docType package
#' @name gClusters
#'
#' @param data A data frame. See also `pre_process()`.
#' @param ncluster A number of clusters.
#' @param elbow.max A number of the maximum value of x-axis. It should be larger
#' than the expected `ncluster` and smaller than the sample size.
#' @param iter.max A number of the maximum iterations allowed in k-means.
#' @param nstart A number of random attempts of generating initial
#' configurations. The k-means algorithm will choose the best one among these
#' attempts. For larger data, 'nstart' can be set lower or just set to 1.

#'
#' @returns A list of 2:
#' @examples data(test_data)
#' reslist <- gClusters(test_data_processed)
#' # k-means result
#' reslist[[1]]
#' # elbow plot
#' reslist[[2]]
#'
#' @importFrom ggplot2 ggplot geom_line aes labs
#' @importFrom purrr map_dbl
#' @importFrom dplyr select
#' @export
gClusters <- function(data, ncluster = 20, elbow.max = 50, ...) {
  runlist <- seq(from = 1, to = elbow.max, length.out = 5)
  wss <- map_dbl(runlist, ~ {
    kmeans(select(data, -c(ID, type)), ...)$tot.withinss
  })
  elbow_df <- as.data.frame(cbind("n_clust" = runlist, "wss" = wss))
  p <- ggplot(elbow_df) +
    geom_line(aes(y = wss, x = n_clust), colour = "#82518c") +
    labs(
      title = "K Means Clustering Using the Elbow Method",
      x = "Number of clusters", y = "Within Sum of Squares (WSS)"
    )
  clusters <- kmeans(select(data, -c(ID, type)), ncluster)
  list(clusters, p)
}
