#' gClusters
#'
#' @description `gClusters` returns the clusters generated by k-means and yield
#' an elbow plot as a way of finding the optimal parameter.
#'
#' @details This function could be ran without any parameters except `data` at
#' the very beginning. After that, users are expected to tune the values
#' according to the clusters and elbow plot. To determine the optimal number
#' of `ncluster`, select the value at where the graph has a rapid change. You
#' may also increase the elbow.max if the data is very large or complicated.
#' @docType package
#' @name gClusters
#'
#' @param data A data frame generated by gData().
#' @param ncluster A number of clusters.
#' @param iter.max A number of the maximum iterations allowed in k-means.
#' @param nstart A number of random attempts of generating initial
#' configurations. The k-means algorithm will choose the best one among these
#' attempts. For larger data, 'nstart' can be set lower or just set to 1.
#' @param elbow.max A number of the maximum value of x-axis. It should be larger
#' than the expected `ncluster` and smaller than the sample size.
#'
#' @returns A list of 2:
#' @examples data(FuncExample)
#' head(a)
#' reslist <- gClusters(a)
#' # k-means result
#' reslist[[1]]
#' # elbow plot
#' reslist[[2]]
#'
#' @importFrom ggplot2 ggplot geom_line aes labs
#' @importFrom purrr map_dbl
#' @export
gClusters <- function(data, ncluster = 20, elbow.max = 50, ...) {
  runlist <- seq(from = 1, to = elbow.max, length.out = 5)
  wss <- map_dbl(runlist, ~ {
    kmeans(select(data, -c(ID, type)), ...)$tot.withinss
  })
  elbow_df <- as.data.frame(cbind("n_clust" = runlist, "wss" = wss))
  p <- ggplot(elbow_df) +
    geom_line(aes(y = wss, x = n_clust), colour = "#82518c") +
    labs(
      title = "K Means Clustering Using the Elbow Method",
      x = "Number of clusters", y = "Within Sum of Squares (WSS)"
    )
  clusters <- kmeans(select(data, -c(ID, type)), ncluster)
  list(clusters, p)
}
